### ISSUE TITLE
Top Gear Rally sound skipping issue

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-gui#20]
Every 1 minute or so, there is a sudden skipping/freezing in the music. If i use sound sync, the game also freezes with the music for that tiny duration. With sync off, the game runs smoothly and only the music has the problem.

The behavior is different than in Project 64 + Azimer where there's some crackling every now and then.

I wonder if this game will ever get perfect sound (i know sound was always completely broken in this game until recently).

**Comment by loganmc10** [comment]
Yeah all the Boss Games have some issue with the sound. If you play Twisted Edge Snowboarding, you'll get some static about every minute or so as well. World Driver Championship has some weird sound every now and then as well. Changing "CountPerOp" to 1 in the core options fixes it in World Driver Championship for me, but messing with CountPerOp in Twisted Edge makes the game run either really fast or really slow.

I haven't tried messing with CountPerOp in Top Gear Rally, I never noticed any audio issues there, although it doesn't surprise me you ran into some. Unfortunately both mupen64plus and project64 have really inaccurate emulation of something called the COUNT register, which is used for timing. Until a solution to that problem is found, it's unlikely that these games will have perfect audio. Although they do sound a lot better today than they did a month ago!

**Comment by loganmc10** [comment]
I'm going to close this since it isn't a problem with the GUi, it's likely a problem with mupen64plus-core, and probably a fairly hard problem to solve at that
