### ISSUE TITLE
Compressed ROM support

### ISSUE THREAD

**Issue by tony971** [m64p/mupen64plus-gui#5]
.rar, .zip, .7z, etc.

**Comment by loganmc10** [comment]
I'll look into this after I get controller configuration and cheats done. .rar support is unlikely given its proprietary nature, but 7z and zip (and gz) support is definitely possible.

It's a little easier for m64py to accomplish this sort of thing, since Python has libraries for these tasks, Qt/C++ has no built in libraries for 7z or zip support, so in order to support them the source code for minizip and 7z/lzma will need to be compiled in with the project.

**Comment by loganmc10** [comment]
I'm going on close this one. There is no reason that every frontend should need to implement this separately. If it was to be implemented, the best place for it would be mupen64plus-core. That way, any frontend could just pass a compressed ROM to the core and have it read it.

I believe mupen64plus-core already compiles in minizip for other reasons, so zip support should be relatively easy I would think.

Feel free to open an issue there: https://github.com/mupen64plus/mupen64plus-core
